# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prouser',
            field=models.BooleanField(default=False),
        ),
    ]
