# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_prouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
